In [74]:
from sklearn.model_selection import cross_val_score,KFold
from sklearn.ensemble import VotingClassifier,BaggingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import MinMaxScaler,LabelEncoder
from imblearn.over_sampling import SMOTE
import pandas as pd
import numpy as np

In [75]:
dataframe = pd.read_csv(r'C:\Users\DELL\Desktop\AI ML\DATA SETS\Wine_data_supervised_classification.csv')
dataframe = np.asarray(dataframe)
X = dataframe[:,0:11]
Y = dataframe[:,11].ravel()
enc = LabelEncoder()
Y = enc.fit_transform(Y)
X = MinMaxScaler().fit_transform(X)

In [76]:
dataframe.shape

(1599, 12)

In [77]:
np.unique(dataframe[:,11],return_counts=True)

(array([3., 4., 5., 6., 7., 8.]),
 array([ 10,  53, 681, 638, 199,  18], dtype=int64))

In [78]:
kfold = KFold(n_splits=3,random_state=8,shuffle=True)
base_cls = DecisionTreeClassifier()
Y = Y.ravel()
model = BaggingClassifier(base_estimator=base_cls,n_estimators=500,random_state=8)
results = cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

0.6722951844903066


In [79]:
estimator = []
estimator.append(('SVC',SVC(gamma='auto',probability=True)))
estimator.append(('LR',LogisticRegression(solver='lbfgs',multi_class='multinomial',max_iter=10000)))
estimator.append(('DTC',DecisionTreeClassifier()))
voting_cls = VotingClassifier(estimators=estimator,voting='soft')
results = cross_val_score(voting_cls, X, Y, cv=kfold)
print(results.mean())

0.6160100062539087


AFTER APPLYING SMOTE

In [80]:
sm = SMOTE()
X,Y = sm.fit_resample(X,Y)
np.unique(Y,return_counts=True)

(array([0, 1, 2, 3, 4, 5], dtype=int64),
 array([681, 681, 681, 681, 681, 681], dtype=int64))

In [81]:
kfold = KFold(n_splits=3,random_state=8,shuffle=True)
base_cls = DecisionTreeClassifier()
Y = Y.ravel()
model = BaggingClassifier(base_estimator=base_cls,n_estimators=500,random_state=8)
results = cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

0.8534018600097895


In [82]:
estimator = []
estimator.append(('SVC',SVC(gamma='auto',probability=True)))
estimator.append(('LR',LogisticRegression(solver='lbfgs',multi_class='multinomial',max_iter=10000)))
estimator.append(('DTC',DecisionTreeClassifier()))
voting_cls = VotingClassifier(estimators=estimator,voting='soft')
results = cross_val_score(voting_cls, X, Y, cv=kfold)
print(results.mean())

0.77141458639256
